        <table id="table_journal_list">
            <tr class="list_header">
                <th>id</th>
                <th>titolo</th>
                <th>data</th>
                <th>ordine</th>
                <th>publico</th>
                <th style="width: 16px">&nbsp;</th>
            </tr>
            <?php foreach($this->post_list as $post) {?>
            <tr>
           		<td><?php echo $post->getId();?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'journal', 'action' => 'edit-post', 'journal_id' => $this->journal->getId(),'postId'=> $post->getId(), 'lang' => $this->lang),'admin', true);?>"><?php echo $post->getTitle();?></a></td>
                <td><?php echo new Zend_Date($post->getStartDate());?></td>
                <td><?php echo $post->getRank();?></td>
                <td><div class="ico_<?php echo ($post->getIsPublic() == 1) ? "yes" : "no" ?>"/></td>
            </tr>


            <?php }?>
            <tr >
            <td colspan="6" style="">
            <div onclick="javascript: window.location.href='<?php echo $this->url(array('controller' => 'journal', 'action' => 'edit-post', 'journal_id' => $this->journal->getId()),'admin', true);?>' "style="" class="ui-corner-all ui-button ui-widget ui-state-default"><img src="/images/admin/new_full.png"></div>
            <?php if ($this->show_settings) {?>

            <div style="float:right;" class="ui-corner-all ui-button ui-widget ui-state-default">
					<a href="<?php echo $this->url(array('controller' => 'page', 'action' => 'show', 'pageId' => $this->journal->getPageId()),'admin', true);?>"><img src="/images/admin/settings.png"></a>
			</div>

            <? }?>
             <?php if ($this->show_list) {?>
            	<div onclick="javascript: window.location.href='<?php echo $this->url(array('controller' => 'journal', 'journal_id' => $this->journal->getId(),'action'=>'show'),'admin', true);?>'" style="float:right;" class="ui-corner-all ui-button ui-widget ui-state-default"><img src="/images/admin/list_full.png"></div>
            <?php }?>


            <br style="clear:both">
            </td></tr>
        </table>