<form enctype="multipart/form-data" name="save_post" id="save_post" method="POST" action="<? echo $this->url(array('action' => 'save-post')) ?>">

    <div class="command_bar post alignRightContent">
        <div style="float:left;background: white;padding:0.1em;border:1px solid black;" class="ui-corner-all ui-button ui-widget">
            <a href="<?php echo $this->url(array('controller' => 'journal', 'action' => 'show', 'journal_id' => $this->journal->getId(), 'lang' => $this->lang), 'admin', true); ?>"><img border="0" src="/images/admin/list_full.png"></a>
        </div>
        <input type="image" src="/images/admin/save_full.png" class="button save" name="submit[SAVE]"/>
        <?php if ($this->post->getId() > 0) { ?>
            <input type="image" src="/images/admin/delete_full.png" name="submit[DEL]"  class="button delete" value="cancella" onclick="javascript:confirmDelete($('#save_post'));"/>
        <?php } ?>
    </div>
    <br style="clear:both"/>
    <div style="float:left;width:800px;margin-right: 10px;" id="page_details_accordion">
        <h3><a href="#">Titolo e descrizione</a></h3>
        <div>
            <input type="hidden" name="post_id" value="<? echo $this->post->getId() ?>"/>
            <input type="hidden" name="journal_id" value="<? echo $this->journal->getId() ?>"/>
            <div style="margin-bottom: 10px">
                <?php if ($this->journal->getShowTitle()) { ?>
                    <input type="text" style="width:100%" name="title" id="title" value="<?php echo $this->post->getTitle() ?>">
                <?php } ?>
            </div>
            <div style="margin-bottom: 10px">
                <?php if ($this->journal->getShowAbstract()) { /*?>
                    <h3 style="margin-bottom: 5px;">Abstract</h3>
                    <div>
                        <!-- <textarea id="text_abstract" name="text_abstract" style="width:100%;height:200px;padding: 5px;"><?php echo $this->post->getTextAbstract(); ?></textarea>-->
                        <?php
                        $content = new Bones_Utils_Editor('text_abstract');
                        $content->setHeight('200');
                        $content->setToolbarSet(Bones_Utils_Editor::TOOLBAR_MINIMAL);
                        $content->setValue($this->post->getTextAbstract());
                        $content->create();
                        ?>
                    </div>
                <?php  */}?>
            </div>
        </div>
        <?php if ($this->journal->getShowFullText()) { ?>
            <h3><a href="#">Contenuto</a></h3>
            <div>
                <?php
                $content = new Bones_Utils_Editor('content');
                $content->setHeight('400');
                $content->setToolbarSet(Bones_Utils_Editor::TOOLBAR_MINIMAL);
                $content->setValue(stripslashes($this->post->getContent()));
                $content->create();
                ?>
            </div>
        <?php } ?>

    </div>
    <div style="float:left;width:250px;">
        <div id="page_edit_accordion">
            <h3><a href="#">Dettagli Articolo</a></h3>
            <div>
                <table>
                    <tr><th>Data</th></tr>
                    <tr><td><input id="start_date" name="start_date" type="text" class="input_calendar" value="<? echo $this->post->getStartDate() ?>"></td></tr>
                    <tr><th>Pubblico</th></tr>
                    <tr><td><input id="is_public" name="is_public" type="checkbox" value="1" <?php
                    if ($this->post->getIsPublic() == 1) {
                        echo "checked";
                    }
                    ?>></td></tr>
                </table>

            </div>
        <?php if ($this->journal->getShowFileUpload()) {?>
        <h3><a href="#">File</a></h3>
        <div>
            <div>
                <?php if ($this->post->getFileId() > 0) { ?>
                    <b>File Caricato</b>:
                    <br>
                    <a href="<?php echo $this->post->getFile()->getFullPath(); ?>" target="_blank"><?php echo $this->post->getFiles()->getFilename() ?></a>
                    <?php } else { ?>

                    <? } ?>
            </div>
                <select name="file_type">
                    <option value="DOC">document</option>
                    <option value="IMG">image</option>
                </select>
            <input type="file" name="post_file_upload" id="post_file_upload"/>
        </div>
        <?php } ?>
        </div>
    </div>
</form>