<img src="/images/upcoming_shows.png"/>
<? foreach ($this->news as $news) { ?>
    <div class="post">
        <div class="flyer_container">
            <?if ($news->getFileType() == JournalPost::FILE_IMG) {
                $image = $news->getFile(); ?>
                <a class="flyer_img" href="<? echo  $image->getFullPath(1024) ?>" rel="photogallery[bonesGallery]" style="display:block;background: url('<? echo $image->getFullPath(150); ?>')  no-repeat center center;"><img src="/images/scotch.png"/></a>
                <!-- div  /></div-->
            <? } else { ?>
                <a class="flyer_img" style="background: url('/images/flyer_default.jpg') no-repeat center center;display:block;"><img  src="/images/scotch.png"/></a>
            <? }?>
        </div>
        <h4><?echo $news->getSmartStartDate(); ?> - <? echo $news->getTitle() ?></h4>
        <div class="post_content left"><? echo $news->getAbstractFromContent() ?></div>
        <div style="height: 10px" class="clear">&nbsp;</div>
        <div class="main_separator clear"></div>
    </div>
    <?
}?>

<?php echo $this->partial('partial/paginator.phtml', array('pager' => $this->pager)); ?>
