<script type="text/javascript">
 $(document).ready(function(){

	 $('#input').css('border: 0');
	 $('#acl_list').jqGrid({
		   url: '/admin/'  + site_lang + '/acl/get-data',
		   datatype: "json",
		   colNames:['id','Tipo', 'id gruppo', 'risorsa','azioni','permesso'],
		   colModel:[ {name:'Id',index:'Id', width:55},
		   		   {name:'role_type',index:'role_type', width:90,editable:true},
		   		   {name:'role_id',index:'role_id', width:100,editable:true},
		   		   {name:'resource',index:'resource', width:80, align:"left",editable:true},
		   		   {name:'action',index:'action', width:300, align:"left",editable:true},
		   		   {name:'permission',index:'permission', width:100,align:"right",editable:true},
		   ],
		   rowNum:10,
		   rowList:[10,20,30],
		   pager: '#pager2',
		   sortname: 'id',
		   viewrecords: true,
		   sortorder: "desc",
		   caption:"ACL per Limelight",
		   editurl:'/admin/'  + site_lang + '/acl/save'
	});
    jQuery("#acl_list").jqGrid('navGrid','#pager2',{edit:false,add:false,del:false});

    $("#bedata").click(function(){
       var gr = jQuery("#acl_list").jqGrid('getGridParam','selrow');
       if( gr != null ){
        jQuery("#acl_list").jqGrid('editRow', gr);
        this.disabled = 'true';
        jQuery("#savedata,#restore").attr("disabled",false);
       } else alert("Please Select Row");
    

    $('#savedata').click(function(){
    	jQuery("#acl_list").jqGrid('saveRow',gr);
    	jQuery("#savedata,#restore").attr("disabled",true);
    	jQuery("#bedata").attr("disabled",false);
    });

    jQuery("#restore").click( function() {
        jQuery("#acl_list").jqGrid('restoreRow',gr);
        jQuery("#savedata,#restore").attr("disabled",true);
        jQuery("#bedata").attr("disabled",false);
         });


    $("#new").click(function(){ jQuery("#acl_list").jqGrid('editGridRow',"new",{height:280,reloadAfterSubmit:false}); });
    $("#delete").click(function(){ var gr = jQuery("#delgrid").jqGrid('getGridParam','selrow'); if( gr != null ) jQuery("#delgrid").jqGrid('delGridRow',gr,{reloadAfterSubmit:false}); else alert("Please Select Row to delete!"); });
  });
});
</script>

<table id="acl_list"></table>

<div id="pager2"></div>
<div style="margin-top: 10px">
    <input type="button" id="bedata" class="button" value="Edit Selected" />
    <input type="button" id="savedata" class="button" value="Save" />
    <input type="button" id="restore" class="button" value="Cancel" />
    <input type="button" id="new" class="button" value="new" />
</div>
