<img src="/images/news.png">

<? foreach ($this->news as $news) { ?>
    <div class="post">
 <div class="post_thumb_container" >
        <?
            //$news = new JournalPost();
            if ($news->getFileType() == JournalPost::FILE_IMG) {
                $image = $news->getFile();
                ?><a href="<? echo  $image->getFullPath(1024) ?>" rel="photogallery[bonesGallery]"><img src="/images/photo_frame_mid.png"/></a>
                    <div class="post_thumb" style="background: url('<? echo $image->getFullPath(200); ?>') no-repeat center center #03263C;"/></div>
            <? } else { ?>
            <img src="/images/default_news.png"/>
        <? }?>
</div>
        <p class="post_date"> <? echo $news->getSmartStartDate(); ?>  </p>
        <h4><? echo $news->getTitle() ?></h4>
        <div class="post_content">
            <? echo $news->getAbstractFromContent() ?>
    </div>
    <div class="read_more"><a href="<? echo $this->url(array('controller' => 'news', 'action' => 'post', 'slug' => $news->getTitleSlug()), 'news', true) ?>" >read more &raquo;</a></div>
    <div class="main_separator clear"></div>

    </div>
<? } ?>

<?php echo $this->partial('partial/paginator.phtml', array('pager' => $this->pager)); ?>
