<img src="/images/news.png">

<? foreach ($this->news as $news) { ?>
    <div class="post">
        <p class="post_date"> <? echo $news->getSmartStartDate(); ?>  </p>
        <h4><? echo $news->getTitle() ?></h4>
        <div class="post_content">
            <?
            //$news = new JournalPost();
            if ($news->getFileType() == JournalPost::FILE_IMG) {
                $image = $news->getFile();
                ?>
                <div style="width:150px;height:181px;position:relative;float:left;margin-right:10px;">
                    <a href="<? echo  $image->getFullPath(1024) ?>" rel="photogallery[bonesGallery]"><img src="/images/photo_frame_mid.png" style="position:absolute;top:0;left:0;z-index:5;border:0px;"/></a>
                    <div style="background: url('<? echo $image->getFullPath(200); ?>') no-repeat center center #03263C;width:128px; height:128px; position:absolute; top:10px; left:10px;z-index:1;"/></div>
                </div>
        <? }
        echo $news->getAbstractFromContent() ?>
    </div>
    <div class="read_more"><a href="<? echo $this->url(array('controller' => 'news', 'action' => 'post', 'slug' => $news->getTitleSlug()), 'news', true) ?>" >read more &raquo;</a></div>
    <div class="main_separator clear"></div>

    </div>
<? } ?>

<?php echo $this->partial('partial/paginator.phtml', array('pager' => $this->pager)); ?>
