<h2 class="album_title text_shadow_clear"><? echo $this->album->getTitle() ?></h2>
<div class="gallery album">
    <p class="back_to"><a href="/media">Back to albums</a></p>
    <div class="photo_album">
        <?php foreach ($this->photo_list as $photo) { ?>
            <?php $image = $photo->getImage(); ?>
            <a href="<? echo $image->getFullPath(800) ?>" class="thumb" style="background: url('<? echo $image->getFullPath(400) ?>') no-repeat center center;" rel="photogallery[bonesGallery]">&nbsp;</a>
        <?php } ?>
        <br class="clear"/>
    </div>
</div>