<div class="gallery photo">
    <h2><img src="/images/photo_albums.png"/></h2>
    <? foreach($this->albums as $album) {?>
    <div class="gallery_item">
        <a class="thumb"  style="background: url('<? echo $album->getCoverPhotoFullPath(400) ?>') no-repeat center center;" href="<? echo $this->url(array("controller" => "media", "action"=> "album", "slug" => $album->getTitleSlug()), "album", true)?>" style="display:block;">&nbsp;</a>
        <span><? echo $album->getTitle() ?></span>
    </div>
    <? } ?>
    <div class="clear"></div>
</div>
<div class="main_separator clear"></div>

<div class="gallery video">
    <h2><img src="/images/videos"/><h2>
    <div class="gallery_item">
        <a href="http://vimeo.com/15153039" rel="photogallery[videoGallery]" title="Underground Interview">
            <img src="/images/underground_interview.jpg" border="0" width="325" height="189"/></a>
        </a>
    </div>
    <div class="clear"></div>
</div>