<script>
    $(document).ready(function() {
        $( "#journal_details_accordion").accordion({ active: 0 });

    });
</script>
<div style="margin: auto; width: auto">
    <h1>editing journal</h1>
    <form name="edit_album" action="<? echo $this->url(array('action' => 'save')) ?>" method="post" enctype="multipart/form-data">
        <div class="command_bar page alignRightContent">
            <input type="image" src="/images/admin/save_full.png" name="submit[SAVE]" value="salva" class="button save"/>
            <input type="image" src="/images/admin/delete_full.png" name="submit[DEL]" value="cancella" class="button delete" onclick="javascript:confirmDelete($('#edit_album'));"/>
        </div>
        <div id="journal_details_accordion">
            <h3><a>Titolo e descrizione</a></h3>
            <div>
                <input type="hidden" name="journal_id" value="<? echo $this->journal->getId() ?>"/>
                <div style="margin-bottom: 10px">
                    <h3 style="margin-bottom: 5px;">Titolo</h3>  <input type="text" style="width:100%" name="title" id="title" value="<?php echo $this->journal->getTitle() ?>">
                </div>
                <div style="margin-bottom: 10px">
                    <h3 style="margin-bottom: 5px;">Abstract</h3>
                    <div>
                        <?php
                        $fck1 = new Bones_Utils_Editor('text_abstract');
                        $fck1->setValue($this->journal->getTextAbstract());
                        $fck1->setToolbarSet(Bones_Utils_Editor::TOOLBAR_MINIMAL);
                        $fck1->setHeight(200);
                        $fck1->create();
                        ?>
                    </div>
                </div>
            </div>
           <br style="clear: both"/>
        </div>
    </form>
    <br style="clear: both;"/>
</div>