<box>
    <p>
        <a href="http://www.bestoftimes.it" target="_blank">http://www.bestoftimes.it</a><br/>
        <a href="http://www.josephfhayes.tumblr.com/" target="_blank">http://www.josephfhayes.tumblr.com/</a><br/>
        <a href="http://www.anchorsaweighrecords.com" target="_blank">http://www.anchorsaweighrecords.com</a><br/>
        <a href="http://www.blacksailsdesign.com" target="_blank">http://www.blacksailsdesign.com</a><br/>
        <a href="http://ink-limited.com/" target="_blank">http://ink-limited.com/</a><br/>
        <a href="http://grieved.bandcamp.com" target="_blank">http://grieved.bandcamp.com</a><br/>
        <a href="http://aestheticapparatus.com" target="_blank">http://aestheticapparatus.com</a><br/>
        <a href="http://www.gigposters.com" target="_blank">http://www.gigposters.com</a><br/>
    </p>
</box>