<h1>Gallery / List</h1>
<table id="table_page_list">
		<tr class="list_header">
		<th>id</th>
		<th>nome</th>
		<th># albums</th>
		<th>edit</th>
		<th>view</th>
</tr>
<?php foreach($this->gallery_list as $gallery ){ ?>
<tr>
	<td><?php echo $gallery->getId(); ?></td>
	<td><?php echo $gallery->getTitle();?></td>
	<td><?php echo $gallery->countAlbums();?></td>
	<td style="width: 32px;"><div class="ui-state-default ui-corner-all" style="text-align:center;"><a href="<?php echo $this->url(array('action'=>'edit', 'galleryId' => $gallery->getId()));?>"><span class="ui-icon ui-icon-circle-triangle-e"></span></a></div></td>
	<td style="width: 32px;"><div class="ui-state-default ui-corner-all" style="text-align:center;"><a href="<?php echo $this->url(array('controller' => 'album', 'action'=>'list', 'galleryId' => $gallery->getId()));?>"><span class="ui-icon ui-icon-circle-triangle-e"></span></a></div></td>
</tr>

<?php }?>
<tr><td colspan="5" align="left"><a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'edit', 'galleryId' => null));?>" class="ui-button">new gallery</a></td></tr>
</table>
<br style="clear:both"/>
<?php echo $this->partial('partial/paginator.phtml', array('pager' => $this->pager)); ?>

