<div id="contacts">
    <img src="/images/contacts.png">
    <script type="text/javascript">
        $(document).ready(function(){
            activate_emails();
            $('#contact_form').find('input').uniform();

        });
    </script>
    <p>You can contact the band using the addresses below or writing directly using the form on this page.</p>
    <p class="addresses">
        <span>info:</span> <a id="mail_info" href="#"></a><br/>
        <span>booking: </span> <a id="booking" href="#"></a><br/>
    </p>
    <div id="mail_form_container">
      <? echo $this->partial('partial/contacts_form.phtml'); ?>
    </div>
</div>
