<div id="contacts">
    <img src="/images/contacts.png">
    <script type="text/javascript">
        $(document).ready(function(){
            activate_emails();
        });
    </script>
    <p>Contact te band using email addresses below, or find our profile on social network websites.</p>
    <p class="addresses">
        <span>info:</span> <a id="mail_info" href="#"></a><br/>
        <span>booking: </span> <a id="booking" href="#"></a><br/>
        <span>website: </span>  <a href="http://www.bonesofficial.com" target="_blank"/>http://www.bonesofficial.com</a>
    </p>
</div>
