<?php echo $this->track_virtual_page;?>
<script type="text/javascript">
	$(document).ready(function(){boot.index()});
</script>
<div id="slideshow">

<?php
$photos = (array)$this->photos;
shuffle($photos); 
foreach($photos as $photo) {?>
	<?php $image = $photo->getImage();?>
	<img border="0" width="<?php echo $this->width?>" height="<?php echo $image->getHeight($this->width)?>"src="<?php echo $image->getFullPath($this->width);?>" alt="Bones & comfort" />
<?php } ?>
</div>


<div class="hr_engraved">&nbsp;</div>
<div class="page_layer">
	<div style="width: 325px;float:left;margin-right: 10px;">
		<?php echo $this->partial('partial/latest_activities.phtml', array('translator' =>  $this->translator)); ?>
	</div>
	<div style="width: 325px;float:left">
		<?php echo $this->partial('partial/vimeo_video.phtml'); ?>
		<div class="hr_engraved">&nbsp;</div>
		<h1><?php echo $this->translator->_("PRESS_RELEASE")?> </h1>
		<div class="hr_engraved">&nbsp;</div>
		<?php echo $this->partial('partial/latest_press.phtml', array('translator' =>  $this->translator)); ?>
		
	</div>
<br class="clear"/>
</div>

