<div class="left home-main">
    <div class="box">
        <h2>About</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pellentesque bibendum leo in mattis. Donec pharetra eleifend metus, non vestibulum enim molestie non. Fusce quis urna a augue ultrices pellentesque. Pellentesque quis leo quis enim consequat gravida sed id magna. <br/><br/>
            Morbi at dui lorem, vel gravida justo. Nullam porta massa id elit venenatis eu rhoncus purus vulputate. Donec nunc turpis, hendrerit eget ultrices at, ultrices vitae libero. Nunc vitae arcu et lectus auctor sollicitudin. Ut fringilla lobortis purus sed consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.<br/><br/>
            Duis interdum sem sit amet neque suscipit quis ultricies quam vulputate. Donec iaculis dapibus hendrerit. Donec vitae justo elit. Fusce interdum neque vel lorem interdum placerat posuere massa laoreet. Duis nec dolor eu sem tempor vulputate. Phasellus eget purus non justo aliquet euismod. Sed posuere tristique placerat.
        </p>
    </div>
</div>
<div class="left home-side">
    <div class="box">
        <? echo $this->render('partial/facebook_like.phtml', array('fb_url' => $this->fb_url)); ?>
    </div>
</div>
<div class="clear"></div>
