<div class="left home-main">
    <div class="box">
        <h2>About</h2>
        <p>
            HEART is a graphic design studio born in Treviso in 2009.<br/>
            Our focus is printed media: books, magazines, visual identities.<br/>
            Heart Studio is also a Screenprinting Lab.<br/>
            Other than working on commission, we do have a lot of independent projects.<br/>

            <a id="mail_info"></a>
        </p>
    </div>
</div>
<div class="left home-side">
    <div class="box">
        <? echo $this->render('partial/facebook_like.phtml', array('fb_url' => $this->fb_url)); ?>
    </div>
</div>
<div class="clear"></div>
