<?php
/*
 * <object
 data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//"
 type="text/html" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
 width="300" height="410">
 <param name="movie"
 value="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//">
 <param name="quality" value="high">
 <param name="allowNetworking" value="always">
 <param name="wmode" value="transparent">
 <param name="bgcolor" value="#FFFFFF">
 <param name="allowScriptAccess" value="never">
 <object
 data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//"
 type="text/html" width="300" height="410"></object></object>
 *
 <!-- 
 */?>
<div style="width: 100%;text-align:center;padding:10px 0;background: #E8E5BC;">
<object data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=tall/bgcol=E8E5BC/linkcol=562102//" type="text/html" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="150" height="270"><param name="movie" value="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=tall/bgcol=E8E5BC/linkcol=562102//"><param name="quality" value="high"><param name="allowNetworking" value="always"><param name="wmode" value="transparent"><param name="bgcolor" value="#E8E5BC"><param name="allowScriptAccess" value="never">
<!-- <object data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=tall/bgcol=E8E5BC/linkcol=562102//" wmode="transparent" type="text/html" width="150" height="295" ></object> -->
<embed wmode="transparent" width="150" height="270" type="application/x-shockwave-flash" id="player"  name="page_player" src="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=tall/bgcol=E8E5BC/linkcol=562102//" allowfullscreen="false" allowScriptAccesS="never" bgcolor="#E8E5BC"></embed>

</object>
 </div>
 
<?php 
 
/*
<object
	data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//"
	type="text/html" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
	width="300" height="410">
	<param name="movie"
		value="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//">
	<param name="quality" value="high">
	<param name="allowNetworking" value="always">
	<param name="wmode" value="transparent">
	<param name="bgcolor" value="#FFFFFF">
	<param name="allowScriptAccess" value="never">
	<object
		data="http://bandcamp.com/EmbeddedPlayer/album=2055109441/size=grande3/bgcol=FFFFFF/linkcol=4285BB//"
		type="text/html" width="300" height="410"></object></object>
*/
?>
