<div class="background_cd">
    <img src="/images/infwt_cd_box.jpg"/>
    <iframe width="280" height="100" style="position: relative; display: block; width: 300px; height: 100px;" src="http://bandcamp.com/EmbeddedPlayer/v=2/album=2055109441/size=grande/bgcol=FFFFFF/linkcol=2d333a/transparent=true/" allowtransparency="true" frameborder="0"><a href="http://bonescomfort.bandcamp.com/album/in-fat-we-trust">..In Fat we Trust! by Bones &amp; Comfort</a></iframe>
</div>