<ul class="event_list">
<?php
foreach($this->eventList as $event) {
	//$event = new Events();
	$img = $event->getImage();
	$startDate = new Zend_Date($event->getStartDate(),'it_IT');
?>
	<li>
		<p class="ev_stdate">[<?php echo $startDate->get(Zend_Date::DATE_SHORT,Zend_Registry::get('locale'))?>]</p>
		<p class="ev_title"><?php echo $event->getTitle()?></p>
		<p class="ev_address"><?php echo $event->getAddress()?></p>
		<p class="ev_image"><?php echo $img->getFullPath()?></p>	
	
	</li>
<?php 
}
?>
</ul>
