<div class="generic_box fbox">
    <div class="box_content  rounded-corners">
     <div class="lucid_border"></div>
	<iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fbonesofficial&amp;width=300&amp;colorscheme=dark&amp;show_faces=true&amp;stream=false&amp;header=false&amp;height=350" border="0" scrolling="no" frameborder="0" style="border:none;overflow:hidden;width:300px;height:350px;margin: 0 auto;" allowTransparency="false"></iframe>
    </div>
</div>