<div class="generic_box fbox">
    <div class="box_content  rounded-corners">
        <div class="lucid_border"></div>
        <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fbonesofficial&amp;width=300&amp;height=410&amp;colorscheme=light&amp;show_faces=true&amp;border_color=%2303263C&amp;stream=false&amp;header=false&amp;appId=190551664332051" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:410px;" allowTransparency="true"></iframe>
    </div>
</div>