<div id="display" class="clear">
    <div id="home_scroller">
        <div class="navi"></div>
        <div class="scrollable">
            <div class="items">
                <div>
                    <img src="/images/home/01.jpg"/>
                </div>
                <div>
                    <img src="/images/home/02.jpg"/>
                </div>
            </div>
        </div>
    </div>
</div>