<div id="display" class="clear">
    <div id="home_scroller">
        <div class="navi"></div>
        <div class="scrollable">
            <div class="items">
                <? for ($i = 1; $i < 6; $i++) { ?>
                    <div>
                        <img src="/images/band/band_0<? echo $i ?>.jpg"/>
                    </div>
                <? } ?>
            </div>
        </div>
    </div>
    <div id="higlight_panel">
        <div class="panel_content perkele">
            <p class="head">2012 www.perkele.it compilation</p>
            <div class="album_cover">
                <h2 class="text_shadow_clear">Welcome in the mouth of Fuzz</h2>
                <img src="/images/perkele_big.jpg"/>
                 <a class="download_link" href="http://perkele.bandcamp.com/album/desert-sound-vol-iv-cd2" target="_blank"><span>DOWNLOAD</span></a>
            </div>
        </div>
    </div>
</div>