<div id="display" class="clear">
    <div id="home_scroller">
        <div class="navi"></div>
        <div class="scrollable">
            <div class="items">
                <? for ($i = 1; $i < 6; $i++) { ?>
                    <div>
                        <img src="/images/band/band_0<? echo $i ?>.jpg"/>
                    </div>
                <? } ?>
            </div>
        </div>
    </div>
    <div id="higlight_panel">
        <div class="panel_content mothersheep">
            <p class="head">New album out now!</p>
            <div class="album_cover">
                <h2 class="text_shadow_clear">MOTHERSHEEP</h2>
                <a rel="shadowbox[preview_cover];width=810;height=300;" href="/music/mothersheep" onclick="javascript:_gaq.push(['_trackPageview', '/album/mothersheep_preview']);"><img src="/images/mother_cd_display.png"/></a>
                 <a class="download_link" rel="shadowbox[digital];width=1024;height=768;" href="http://www.cdbaby.com/cd/bonescomfort"><span>BUY DIGITAL</span></a>
                 :
                 <a class="download_link" rel="shadowbox[physical];width=1024;height=768;" href="http://www.godownrecords.com/en-UK/mothersheep-disgod080.php"><span>BUY PHYSICAL</span></a>
                 :
                 <a rel="shadowbox[preview_link];width=810;height=300;" href="/music/mothersheep" onclick="javascript:_gaq.push(['_trackPageview', '/album/mothersheep_preview']);"><strong>LISTEN</strong></a>
            </div>
        </div>
    </div>
</div>

