<div class="press_home">
<p>
	<a target="_blank" href="http://www.italiadimetallo.altervista.org/recensioni_cd/bones_comfort_in_fat_we_trust.htm">http://www.italiadimetallo.altervista.org/</a><br/>
	<a target="_blank" href="http://www.noizeitalia.com/index.asp?pag=recensioni2&id=2679">http://www.noizeitalia.com/</a><br/>
	<a target="_blank" href="http://deleremundi.blogspot.com/2009/12/bones-comfort.html">http://deleremundi.blogspot.com/</a><br/>
	<a target="_blank" href="http://www.flashmagazine.it/edicola/bones&comfort.htm">http://www.flashmagazine.it/</a><br/>
</p>
<p style="float:right;padding-right: 5px;"><a href="javascript:void(0)" class="ajaxLink" rel="<?php echo $this->url(array('controller' => 'press', 'action' => 'index'));?>"><?php echo $this->translator->_("VIEW_ALL"); ?> &raquo;</a></p>
</div>