<div class="press_home">
<p>
	<a target="_blank" href="http://insane-riez.blogspot.com/2010/01/in-fat-we-trust.html">http://insane-riez.blogspot.com</a><br/>
	<a target="_blank" href="http://www.noizeitalia.com/index.asp?pag=underground2&id=107">http://www.noizeitalia.com/ interview </a><br/>
	<a target="_blank" href="http://www.metal.it/album.aspx/11138/">http://www.metal.it/</a><br />		
	<a target="_blank" href="http://markfishers-musicreview.blogspot.com/2009/12/bones-and-comfort-in-fat-we-trust.html">http://markfishers-musicreview.blogspot.com</a> 
	<a target="_blank" href="http://deleremundi.blogspot.com/2009/12/bones-comfort.html">http://deleremundi.blogspot.com/</a><br/>
	
</p>
<p style="float:right;padding-right: 5px;"><a href="javascript:void(0)" class="ajaxLink" rel="<?php echo $this->url(array('controller' => 'press', 'action' => 'index'));?>"><?php echo $this->translator->_("VIEW_ALL"); ?> &raquo;</a></p>
</div>