<div class="generic_box">
    <div class="main_separator"></div>
    <h2><img src="/images/news.png"/></h2>
    <div class="box_content  rounded-corners">
        <div class="lucid_border"></div>
        <? foreach ($this->posts as $post) { ?>
            <div class="item">
                <h3 class="text_shadow_dark"><a href="<? echo $this->url(array("controller"=>"news", "action"=>"post", "slug" => $post->getTitleSlug()), 'news', true) ?>"><? echo $post->getTitle() ?></a></h3>
            </div>
        <? } ?>
    </div>
</div>