<div id="download_iftw">
	<a href="http://bonescomfort.bandcamp.com/album/in-fat-we-trust?action=buy&from=embed" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/download/infatwetrust']);" ><img src="/images/ifwt_download.png" alt="download In Fat We Trust" border="0"/></a>
</div>
<div id="silouettes"><?php echo $this->partial('partial/silouettes.phtml',array("translator" => $this->translator, "latestShows" => $this->latestShows));?></div>


<div id="right_content">
	<div class="page_layer">
	<?php echo $this->partial("partial/band_camp_player.phtml");?>
	</div>
	<?php echo $this->partial('partial/fb_fanbox.phtml'); ?>
</div>
