<div class="generic_box shows">
    <div class="main_separator"></div>
    <h2><img src="/images/upcoming_shows.png"/></h2>
    <div class="box_content">
        <div class="lucid_border"></div>
        <? foreach ($this->posts as $post) { ?>
            <div class="item">
                <p class="date text_shadow_dark"><? echo $post->getSmartCreated() ?></p>
                <p class="title text_shadow_dark"><? echo $post->getTitle() ?></p>
            </div>
        <? } ?>
    </div>
</div>