<div id="external_links">
	<a target="_blank" href="http://www.facebook.com/pages/Bones-Comfort/52988616067" alt="facebook" ><img title="facebook" border="0" width="32" height="32" src="/images/facebook_32.png"></a>
	<a target="_blank" href="http://www.lastfm.it/music/Bones%2B%2526%2BComfort" alt="last-fm"><img title="last-fm" border="0" width="32" height="32" src="/images/lastfm_32.png"></a>
	<a target="_blank" href="http://www.myspace.com/bonesofficial" alt="myspace"><img border="0" title="myspace" width="32" height="32" src="/images/myspace_32.png"></a>
	<a target="_blank" href="http://bonescomfort.bandcamp.com/" alt="bandcamp"><img border="0" title="bandcamp" width="32" height="32" src="/images/bandcamp_32.png"></a>
</div>