<div id="social_media">
    <div class="main_separator"></div>
    <div class="icons clear">
        <a target="_blank" href="http://www.facebook.com/pages/Bones-Comfort/52988616067" alt="facebook" ><img title="facebook" border="0"  src="/images/media-icon/facebook.png"></a>
        <a target="_blank" href="http://www.lastfm.it/music/Bones%2B%2526%2BComfort" alt="last-fm"><img title="last-fm" border="0" src="/images/media-icon/lastfm.png"></a>
        <a target="_blank" href="http://twitter.com/#!/bonesandcomfort" alt="twitter"><img border="0" title="twitter"  src="/images/media-icon/twitter.png"></a>
        <a target="_blank" href="http://www.myspace.com/bonesofficial" alt="myspace"><img border="0" title="myspace"  src="/images/media-icon/myspace.png"></a>
        <a target="_blank" href="http://bonescomfort.bandcamp.com/" alt="bandcamp"><img border="0" title="bandcamp"  src="/images/media-icon/bandcamp.png"></a>
    </div>
    <div class="clear"></div>
</div>
