<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 300,
  height: 300,
  theme: {
    shell: {
      background: '#03263c',
      color: '#ffffff'
    },
    tweets: {
      background: '#03263c',
      color: '#ffffff',
      links: '#f4cfa3'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    behavior: 'all'
  }
}).render().setUser('bonesandcomfort').start();
</script>
<div class="twitter_pad"></div>