<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $("a[rel^='gallery']").prettyPhoto();
        var container = $('#floating_thumbs');

        container.imagesLoaded( function(){
          container.masonry({
            itemSelector : '.work-item'
          });
        });

    });
</script>
<div class="left work-main">
    <div class="work-item-container">
    <div id="floating_thumbs">
        <?
        foreach ($this->work_list as $album) {
            //$album = new Album();
            $photos = (array) $album->getPhotoss();
            if (count($photos) < 1)
                continue;
            $first = array_shift($photos);
            $first_image = $first->getImage();
            ?>
            <div class="work-item">
                <a style="display:block;position:relative;" title="<? echo $album->getTitle() ?>" rel="gallery['<? echo $album->getSluggedIndex() ?>']" href="<? echo $first_image->getFullPath() ?>">
                    <img src="<? echo $first_image->getFullPath(WorksController::DEFAULT_THUMB) ?>" align="absmiddle" border="0"/>
                    <div class="work-item-title"><?php echo $album->getTitle(); ?></div>
                </a>

                <div style="display:none;">
                    <?php
                    foreach ($photos as $photo) {
                        $image = $photo->getImage();
                        ?>
                        <a href="<?php echo $image->getFullPath(600) ?>" title="<? echo $album->getTitle() ?>" rel="gallery['<? echo $album->getSluggedIndex() ?>']" title=""><img border="0" src="<?php echo $image->getFullPath(WorksController::DEFAULT_THUMB) ?>" align="absmiddle"/></a>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="clear" style="height:30px"></div>
</div>
</div>
<div class="left work-side">
    <? echo $this->render('partial/facebook_like.phtml', array('fb_url' => $this->fb_url)); ?>
</div>
<div class="clear"></div>

