<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $("a[rel^='gallery']").prettyPhoto();
    });
</script>
<h2><? echo $this->work->getTitle() ?></h2>
<p><? echo $this->work->getDescription() ?></p>
<div class="work-gallery-container">
    <?php foreach ($this->image_list as $photo) { ?>
        <?php $image = $photo->getImage(); ?>
        <div class="ui-corner-all work-gallery-item">
            <div class="work-gallery-thumb" style="background: url('<?php echo $image->getFullThumbPath(WorksController::DEFAULT_THUMB) ?>') top center">
                <a href="<?php echo $image->getFullPath(800) ?>" rel="gallery[work]" title=""><img border="0" src="/images/pix.gif" align="absmiddle"/></a>
            </div>
        </div>
    <?php } ?>
</div>
