<div>
<form name="admin_login" id="admin_login" method="post" action="<?php echo $this->url(array('action' => 'doLogin'));?>">
<table id="login_table">
	<tr>
		<th>username</th><td><input type="text" name="username" value="" id="username"/></td>
	</tr>
	<tr>
		<th>password</th><td><input type="password" name="password" value="" id="password"/></td>
	</tr>
	<tr>
		<th></th><td><input type="submit" name="login" value="login"/></td>
	</tr>
</table>
</form>
</div>