<?php echo $this->doctype() ?>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>HEART STUDIO ADMIN</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <script>
            var lang = '<?php echo $this->lang; ?>';
        </script>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>

        <script src="/js/admin.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="header">
            <h3>Heart Studio Admin</h3>
        </div>
        <div class="ui-tabs ui-widget ui-widget-content ui-corner-all">
            <?php echo $this->partial('partial/admin/main_menu.phtml', array("logged" => $this->logged, "main_menu" => $this->main_menu, "selected_page" => $this->selected_page)) ?>
            <div id="main_content" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
                <?php echo $this->partial('partial/admin/error_messages.phtml', array('error_messages' => $this->error_messages)) ?>
                <?php echo $this->layout()->content ?>
            </div>
        <br class="clear">
        </div>
    </body>

</html>