<?php echo $this->doctype() ?>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bonesofficial.com admin</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <script>
	    	var lang = '<?php echo $this->lang;?>';
	</script>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>

    <script src="/js/admin.js" type="text/javascript"></script>
</head>
<body>
<div id="header">
	<h3>Bonesofficial.com Admin</h3>
</div>
<?php if ($this->logged) {?>
<ul id="main_menu">
	<?php foreach ($this->main_menu as $entry) {?>
		<li><a href="<?php echo $entry['url']?>"><?php echo $entry['name']?></a></li>
	<?php }?>
</ul>
<?php }?>
<div id="main_content">
 	<?php echo $this->partial('partial/admin/error_messages.phtml', array('error_messages' => $this->error_messages))?>
	<?php echo $this->layout()->content ?>
</div>
</body>

</html>