<?php echo $this->doctype() . "\n"; ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bones & Comfort - <?php echo $this->page_title?></title>
    <meta property="fb:page_id" content="52988616067" />
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <script type="text/javascript">
    	var lang = '<?php echo $this->lang;?>';
    </script>
    <script src="http://cdn.jquerytools.org/1.2.5/jquery.tools.min.js"></script>
    <?php echo $this->headScript() ?> 
  	<script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-12833462-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

</script>
</head>	    
<body>
    <div id="content">
        <a class="prev browse left"></a>
        <div class="scrollable">
            <div class="items">
                <?php echo $this->layout()->content ?>
                <div id="bio" class="page_content"></div>
                <div id="music" class="page_content"></div>
                <div id="contact" class="page_content"></div>
            </div>
            </div>

        <!-- "next page" action -->
        <a class="next browse right"></a>
    </div>
</body>
</html>