<?php echo $this->doctype() . "\n"; ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Heart Studio</title>
        <link rel="shortcut icon" href="/images/favicon.ico"/>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <script type="text/javascript">
            var lang = '<?php echo $this->lang; ?>';
        </script>
        <?php echo $this->headScript() ?>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-27107614-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </head>
    <body class="splash">
        <div id="wrapper">
            <div id="main_content">
                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
            <div class="push"></div>
        </div>
    </body>
</html>
