<script>
$(document).ready(function() {
	$( "#album_details_accordion").accordion({ active: 1 , autoHeight: false});
	
});
</script>
<div style="margin: auto; width: auto">
    <h1>edit::album:<span><? echo $this->album->getTitle()?></span></h1>
    <div style="margin: 0 0 5px 0;"><a href="<?php echo $this->url(array('action'=>'photos','albumId'=> $this->album->getId()));?>">edit album photos</a></div>
    <form name="edit_album" action="<? echo $this->url(array('action'=>'save'))?>" method="post" enctype="multipart/form-data">
    <div class="command_bar page alignRightContent">
		<input type="image" src="/images/admin/save_full.png" name="submit[SAVE]" value="salva" class="button save"/>
		<input type="image" src="/images/admin/delete_full.png"" name="submit[DEL]" value="cancella" class="button delete" onclick="javascript:confirmDelete($('#edit_album'));"/>
	</div>
    <div id="album_details_accordion">
    	<h3><a>Titolo e descrizione</a></h3>
		<div>
		    <input type="hidden" name="galleryId" value="<? echo $this->gallery->getId()?>"/>
		    <input type="hidden" name="id" value="<? echo $this->album->getId()?>"/>
		    <div style="margin-bottom: 10px">
		        <h3 style="margin-bottom: 5px;">Titolo</h3>  <input type="text" style="width:100%" name="title" id="title" value="<?php echo $this->album->getTitle()?>">
		     </div>
		     <div style="margin-bottom: 10px">
		        <h3 style="margin-bottom: 5px;">Descrizione</h3>
		        <div style="width:300px;float:left;">
		            <?php 
		    		$fck1 = new Bones_Utils_Editor('description');
		    		$fck1->setValue($this->album->getDescription());
		    		$fck1->setToolbarSet(Bones_Utils_Editor::TOOLBAR_MINIMAL);
		    		$fck1->setHeight(200);
		    		$fck1->create();
		    		?>
		        </div>
		     </div>
		     <div style="float:left;margin-left:10px;">
				<h3 style="margin-bottom: 5px;">Images Max Width</h3>
			    <div><input type="text" style="width:40px" name="max_width" id="title" value="<?php echo $this->album->getMaxWidth()?>"> px</div>
			    <h3 style="margin-bottom: 5px;">Images Max height</h3>
			    <div><input type="text" style="width:40px" name="max_height" id="title" value="<?php echo $this->album->getMaxHeight()?>"> px</div>
			    <div style="margin-bottom: 10px">
		       		<h3 style="margin-bottom: 5px;">Pubblico</h3>  <input type="checkbox" name="is_public" id="is_public" value="1" <?php echo ($this->album->getIsPublic()) ? "checked" : ""?>>
		     	</div>
			 </div>
		     
		</div>
	<br style="clear: both;"/>
</div>