<div style="margin: auto; width: auto">
    <h1>Album / <span><? echo $this->album->getTitle() ?></span> / Edit</h1>
    <div style="margin: 0 0 5px 0;"><a href="<?php echo $this->url(array('action' => 'photos', 'albumId' => $this->album->getId())); ?>">manage photos</a></div>
    <form name="edit_album" action="<? echo $this->url(array('action' => 'save')) ?>" method="post" enctype="multipart/form-data">
        <div class="command_bar page alignRightContent">
            <input type="image" src="/images/admin/save_full.png" name="submit[SAVE]" value="salva" class="button save ui-corner-all"/>
            <input type="image" src="/images/admin/delete_full.png" name="submit[DEL]" value="cancella" class="button delete ui-corner-all" onclick="javascript:confirmDelete($('#edit_album'));"/>
        </div>
        <? echo $this->partial("partial/album_editor.phtml", array('album' => $this->album, 'gallery' => $this->gallery)); ?>
    </form>
</div>