<h1>Album List</h1>
	<div style="margin-top: 10px">
	<?php if (isset($this->galleryId)) {?>
	 		<div style="line-height: 150px;margin: 10px;padding: 10px;text-align:center;float:left; width:150px; border: 1px solid #666;" class="ui-corner-all">
            <div style="height:25px;line-height:25px;">create new</div>
            <div style="border:1px solid black;height:150px;overflow:hidden;width:100%;padding:0px;">
            <a href="<?php echo $this->url(array('controller' => 'album', 'action' => 'new','galleryId'=> $this->galleryId, 'lang' => $this->lang),'admin', true);?>">
            	<img src="/images/admin/new.png" style="" align="middle" border="0"/></a>
            </div>
         </div>
        <?php }
        foreach($this->album_list as $album) {?>
		<?php  
			//$album = new Album();
			$cover = $album->getCoverPhoto();
			$image = $cover->getImage();
			$path = ($image->getFilename() != null) ? $image->getFullPath(Bones_Files_Image::THUMB_WIDTH) : "/images/admin/default_album_cover.jpg"?>
            <div style="line-height: 150px;margin: 10px;padding: 10px;text-align:center;float:left; width:150px; border: 1px solid #666;" class="ui-corner-all">
            <div style="height:25px;line-height:25px;"><?php echo $album->getTitle();?></div>
            <div style="border:1px solid black;height:150px;overflow:hidden;width:100%;padding:0px;">
            <a href="<?php echo $this->url(array('controller' => 'album', 'action' => 'photos','albumId'=> $album->getId(), 'lang' => $this->lang),'admin', true);?>">
            	<img src="<?php echo $path?>" style="width:100%;" align="middle" border="0"/></a>
            </div>
            	<div style="height:25px; width:150px; text-align: center; line-height:25px;position:relative;"><div class="ico_<?php echo ($album->getIsPublic() == 1) ? "yes" : "no" ?>" style="position:absolute;left:50%"/></div></div>
            </div>
           <?php }?>
    </div>
