<div style="margin: auto; width: auto">
    <h1>Albums / New</h1>
    <form name="edit_album" action="<? echo $this->url(array('action' => 'save')) ?>" method="post" enctype="multipart/form-data">
        <div class="command_bar page alignRightContent">
            <input type="image" src="/images/admin/save_full.png" name="submit[SAVE]" value="salva" class="button save ui-corner-all"/>
        </div>
        <? echo $this->partial("partial/album_editor.phtml", array('album' => $this->album, 'gallery' => $this->gallery)); ?>
    </form>
    <br style="clear: both;"/>
</div>