<h1>Album / <span><?php echo $this->album->getTitle()?></span> / Photos</h1>
<div style="margin: 0 0 5px 0;"><a href="<?php echo $this->url(array('action'=>'edit','albumId'=> $this->album->getId()));?>">Edit Album</a></div>
<form name="edit_album" action="<? echo $this->url(array('action'=>'save'))?>" method="post" enctype="multipart/form-data">
<input type="hidden" name="galleryId" value="<? echo $this->album->getGalleryId()?>"/>
<input type="hidden" name="id" value="<? echo $this->album->getId()?>"/>
<table>
	<tr>
		<td><input type="file" name="photo" style="border: 1px solid black;"></td>
		<td><input type="image" align="middle" src="/images/admin/new.png" name="submit[ADDPHOTO]" value="aggiungi foto" class="button save ui-corner-all"/></td>
	</tr>
</table>
</form>
<div style="margin-top: 10px">
	<?php foreach($this->photo_list as $photo) {?>
	<?php  $image = $photo->getImage();?>
		<div style="line-height: 150px;margin: 10px;padding: 10px;text-align:center;float:left; width:150px; border: 1px solid #666;" class="ui-corner-all">
			<div style="border:1px solid black;height:150px;overflow:hidden;width:100%;padding:0px;"><img border="0" src="<?php echo $image->getFullPath(Bones_Files_Image::THUMB_WIDTH)?>" style="width:100%;" align="middle"/></div>
			<div style="height:25px;line-height:25px;"><a href="javascript:void(0)" onclick="javascript:confirm_delete_photo('<?echo $photo->getId()?>','<?php echo $photo->getAlbumId()?>');">elimina</a></div>
		</div>
	<?php }?>
</div>
<br style="clear:both">
<?php if ($this->show_list) {?>
<div onclick="javascript: window.location.href='<?php echo $this->url(array('controller' => 'gallery', 'galleryId' => $this->gallery->getId(),'action'=>'show'),'admin', true);?>'" style="float:right;" class="ui-corner-all ui-button ui-widget ui-state-default"><img src="/images/admin/list_full.png"></div>
<?php }?>
