<img src="/images/band_bio.png">

<p>Bones & Comfort saw the light in 2006, born from Daniele's urgency to play some pure hard rock without any frills. After some line-up changes, the band finds the perfect sound with Daniele himself (guitar and vocals), Alberto (bass) and Luca (drums). The main common influences remain the same as the beginning, while Doom, Stoner and Southern came to touch all the compositions.</p>
<p>After a few live shows around Milan, the band started receiving positive feedback both for the songs and the performance live. All the songs are completed, so Bones & Comfort head into the studio at the end of 2008.</p>
<div class="hr_engraved">&nbsp;</div>
<h2>&quot;..In Fat we trust!&quot;</h2>
<p>
    After a few months of hard work and entire nights spent mixing, &quot;…in Fat we trust&quot; is completed by May 2009. The EP contains 5 original songs, self-recorded in their rehearsal room and in a friend’s studio. The result reflects the live attitude of the band and the tracks are filled with warm sounds, heavy riffs and catchy choruses which show what Bones & Comfort are aiming for.</p>
<p>
    The album got positive reviews from web and traditional music press and gave the band more chances to play live. The band then join the compilations &quot;Kill City 19th&quot; (272-Records - USA - 2009) and &quot;LaBelleAlliance&quot; (ValeryRecords - ITA - 2010).
</p>
<h2>What's next?</h2>
<p>
    The band enter on &quot;Morbid Sound Studio&quot; at the beginning of 2011 to record a full lenght album, with 7 brand new songs + two tunes from &quot;..in Fat we trust!&quot;.<br/>
    The album is still now on mixing stage..stay tuned for all news.
<br/><br/><div class="hr_engraved">&nbsp;</div>
<br/><br/>
</p>
