<img src="/images/band_bio.png">
<div id="bio">
    <p>Bones & Comfort are a power trio formed in 2006 by Daniele. His need to play pure rock and roll without frills is shared by Alberto and Luca.</p>
    <p>Bones & Comfort offer a unique blend of rock, blues, stoner trips and southern sounds.</p>
    <p>The first live shows brought lots of positive feedback within the rock community. Bones & Comfort progressively developed their sound and at the end of 2008 the band headed into the studio.<br/> After a few months of hard work and entire nights spent mixing, "…in Fat we trust" is completed. <br/>  The EP contains five original songs and is fully self-produced. The music reflects the attitude of the band and the tracks are filled with warm distortions, heavy riffs and catchy choruses, which have all become trademarks of the Bones & Comfort sound.</p>
    <p>Thanks to the EP’s success on the Italian and foreign press, Bones & Comfort started a season of successful live shows in northern Italy. The band grew even tighter and the creative flow brought them into the studio again in 2011, after roughly one year of songwriting.</p>
    <p>"Mothersheep" was recorded and produced by Luigi Galmozzi at his Morbid Sound Studios. The album contains 9 tracks showcasing Bones & Comfort's live energy, raw guitars and heavy grooves and will be published by GO DOWN RECORDS in 2012.</p>
</div>