<img src="/images/music.png">
<div class="big_separator"></div>
<img src="/images/compilations.png"/>
<div class="clear"></div>
<div class="compilation">
    <img src="/images/perkeleIV.jpg"/>
    <p class="title">Welcome in the mouth of Fuzz</p>
    <p class="label">www.perkele.it</p>
</div>

<div class="compilation">
    <img src="/images/alliance.jpg"/>
    <p class="title">La Belle Alliance Pub</p>
    <p class="label">Valery Records</p>
</div>


<div class="compilation">
    <img src="/images/killcity19.jpg"/>
    <p class="title">Kill City 19th</p>
    <p class="label">272 Records</p>
</div>

