<img src="/images/music.png">
<div id="albums">
    <div class="clear"></div>
    <div class="album_description">
        <h2>...In Fat we trust! (2009)</h2>
        <ol>
            <li>Road Pizza</li>
            <li>We choose who will stand</li>
            <li>Sci-fi Girl</li>
            <li>Modern Times Bacchanalia</li>
            <li>Friday Night</li>
        </ol>
        <p>Label: <strong>Unsigned</strong></p>
        <br/><br/><br/><br/>
        <a class="download_link" href="http://bonescomfort.bandcamp.com/album/in-fat-we-trust?action=buy&from=embed" target="_blank">Download on <span>Bandcamp</span></a>
    </div>
    <div class="album_cover">
        <img src="/images/infwt_cd_box.jpg"/>
    </div>
    <div class="clear">
        <h2 class="text_shadow_clear">Reviews</h2>
<a target="_blank" href="http://www.stereoinvaders.com/index.php?option=com_content&view=article&catid=3:underground&id=4682:bones-and-comfort-in-fat-we-trust&Itemid=16">http://www.stereoinvaders.com</a><br/>
<a target="_blank" href="http://www.rockrebelmagazine.com/cd-reviews-pag-7/">http://www.rockrebelmagazine.com/cd-reviews-pag-7/</a><br/>
<a target="_blank" href="http://www.noizeitalia.com/index.asp?pag=recensioni2&id=2679">http://www.noizeitalia.com/</a><br/>
<a target="_blank" href="http://www.metal.it/album.aspx/11138/">http://www.metal.it/album.aspx/11138/</a><br/>
<a target="_blank" href="http://truemetal.it/modules.php?name=News&file=article&sid=35195">http://truemetal.it/modules.php?name=News&file=article&sid=35195</a><br/>
<a target="_blank" href="http://www.italiadimetallo.altervista.org/recensioni_cd/bones_comfort_in_fat_we_trust.htm">http://www.italiadimetallo.altervista.org/recensioni_cd/bones_comfort_in_fat_we_trust.htm</a><br/>
<a target="_blank" href="http://deleremundi.blogspot.com/2009/12/bones-comfort.html">http://deleremundi.blogspot.com/2009/12/bones-comfort.html</a><br/>
<a target="_blank" href="http://www.flashmagazine.it/edicola/bones&comfort.htm">http://www.flashmagazine.it/edicola/bones&comfort.htm</a><br/>
<a target="_blank" href="http://insane-riez.blogspot.com/2010/01/in-fat-we-trust.html">http://insane-riez.blogspot.com/2010/01/in-fat-we-trust.html</a><br/>
<a target="_blank" href="http://markfishers-musicreview.blogspot.com/2009/12/bones-and-comfort-in-fat-we-trust.html">http://markfishers-musicreview.blogspot.com/2009/12/bones-and-comfort-in-fat-we-trust.html</a> <br/>

    </div>
</div>
<div class="big_separator"></div>
<div id="compilations">
    <img src="/images/compilations.png"/>
    <div class="clear"></div>

    <div class="compilation">
        <img src="/images/perkeleIV.jpg"/>
        <p class="title">Welcome in the mouth of Fuzz</p>
        <p class="label">www.perkele.it</p>
    </div>

    <div class="compilation">
        <img src="/images/alliance.jpg"/>
        <p class="title">La Belle Alliance Pub</p>
        <p class="label">Valery Records</p>
    </div>


    <div class="compilation">
        <img src="/images/killcity19.jpg"/>
        <p class="title">Kill City 19th</p>
        <p class="label">272 Records</p>
    </div>
</div>
