<img src="/images/music.png">
<div id="albums"><?php /*
    <div class="clear"></div>
    <div class="album_description">
        <h2>Mothersheep (2012)</h2>
        <ol>
            <li>We choose who will stand</li>
            <li>Tex mex</li>
            <li>Isaac wife's song</li>
            <li>Unbalance</li>
            <li>Road pizza</li>
            <li>My crusade</li>
            <li>Take some pills</li>
            <li>No country for musicians</li>
            <li>Inhale</li>
            <li>Orange blossoms and four swans</li>
        </ol>
        <p>Label: <strong>godown records</strong></p>
        <br/>
        <a class="download_link" href="http://www.godownrecords.com/en-UK/mothersheep-disgod080.php" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/album/mothersheep_godown_link']);">Buy on <span>Godown Records</span></a>
    </div>
    <div class="album_cover">
        <a class="download_link" href="http://www.godownrecords.com/en-UK/mothersheep-disgod080.php" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/album/mothersheep_godown_link']);"><img src="/images/mother_cd.jpg" border="0"/></a>
    </div>
    <div class="clear"></div>
    <div class="big_separator clear"></div>
 *
 */?>
    <div class="album_description">
        <h2>...In Fat we trust! (2009)</h2>
        <ol>
            <li>Road Pizza</li>
            <li>We choose who will stand</li>
            <li>Sci-fi Girl</li>
            <li>Modern Times Bacchanalia</li>
            <li>Friday Night</li>
        </ol>
        <p>Label: <strong>unsigned</strong></p>
        <br/>
        <a class="download_link" href="http://bonescomfort.bandcamp.com/album/in-fat-we-trust?action=buy&from=embed" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/download/infatwetrust']);">Download on <span>Bandcamp</span></a>
    </div>
    <div class="album_cover">
        <a class="download_link" href="http://bonescomfort.bandcamp.com/album/in-fat-we-trust?action=buy&from=embed" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/download/infatwetrust']);"><img src="/images/infwt_cd.jpg" border="0"/></a>
    </div>
    <div class="clear">
        <h2 class="text_shadow_clear">Reviews</h2>
        <a target="_blank" href="http://www.stereoinvaders.com/index.php?option=com_content&view=article&catid=3:underground&id=4682:bones-and-comfort-in-fat-we-trust&Itemid=16">StereoInvaders</a> -
        <a target="_blank" href="http://www.rockrebelmagazine.com/cd-reviews-pag-7/">Rockrebel Magazine</a> -
        <a target="_blank" href="http://www.noizeitalia.com/bonescomfort-in-fat-we-trust/">NoizeItalia</a> -
        <a target="_blank" href="http://www.metal.it/album.aspx/11138/">Metal.it</a> -
        <a target="_blank" href="http://truemetal.it/modules.php?name=News&file=article&sid=35195">TrueMetal</a> -
        <a target="_blank" href="http://www.italiadimetallo.altervista.org/recensioni_cd/bones_comfort_in_fat_we_trust.htm">Italia di Metallo</a> -
        <a target="_blank" href="http://deleremundi.blogspot.com/2009/12/bones-comfort.html">DelereMundi</a> -
        <a target="_blank" href="http://insane-riez.blogspot.com/2010/01/in-fat-we-trust.html">Insane Riez</a> -
        <a target="_blank" href="http://markfishers-musicreview.blogspot.com/2009/12/bones-and-comfort-in-fat-we-trust.html">Mark Fisher</a> <br/>
    </div>
    <div class="big_separator"></div>
    <div class="clear"></div>

</div>

<div id="compilations">
    <img src="/images/compilations.png"/>
    <div class="clear"></div>

    <div class="compilation">
        <a class="download_link" href="http://perkele.bandcamp.com/album/desert-sound-vol-iv-cd2" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/download/perkeleIV']);"><img src="/images/perkeleIV.jpg" border="0"/></a>
        <p class="title">Welcome in the mouth of Fuzz</p>
        <p class="label">www.perkele.it</p>
        <p><a class="download_link" href="http://perkele.bandcamp.com/album/desert-sound-vol-iv-cd2" target="_blank" onClick="javascript:_gaq.push(['_trackPageview', '/download/perkeleIV']);">DOWNLOAD</a></p>
    </div>

    <div class="compilation">
        <img src="/images/alliance.jpg"/>
        <p class="title">La Belle Alliance Pub</p>
        <p class="label">Valery Records</p>
    </div>


    <div class="compilation">
        <img src="/images/killcity19.jpg"/>
        <p class="title">Kill City 19th</p>
        <p class="label">272 Records</p>
    </div>
</div>
