<div style="padding:10px;">
    <img src="/images/mother_cd_display.png" style="float:left;">
    <div style="float:left;padding:5px;">
        <object height="270" width="500">
            <param name="movie" value="https://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F1737242%3Fsecret_token%3Ds-f4Ktd&amp;show_comments=false&amp;auto_play=false&amp;show_playcount=false&amp;show_artwork=false&amp;color=ff7700"></param> <param name="allowscriptaccess" value="always"></param>
            <embed allowscriptaccess="always" height="270" src="https://player.soundcloud.com/player.swf?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F1737242%3Fsecret_token%3Ds-f4Ktd&amp;show_comments=false&amp;auto_play=false&amp;show_playcount=false&amp;show_artwork=false&amp;color=ff7700" type="application/x-shockwave-flash" width="500"></embed>
        </object>
    </div>
</div>