<?php
// This file generated by Propel 1.5.2 convert-conf target
// from XML runtime conf file /mnt/works/theundir/build/runtime-conf.xml
$conf = array (
  'datasources' =>
  array (
    'ORM' =>
    array (
      'adapter' => 'mysql',
      'connection' =>
      array (
        'dsn' => 'mysql:dbname=Sql496985_1;host=62.149.150.140',
        'user' => 'Sql496985',
        'password' => 'e4737607',
      ),
    ),
    'default' => 'ORM',
  ),
  'generator_version' => '1.5.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-ORM-conf.php');
return $conf;