<?php
// This file generated by Propel 1.5.2 convert-conf target
// from XML runtime conf file /mnt/works/theundir/build/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'ORM' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:dbname=bones;host=127.0.0.1',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'ORM',
  ),
  'generator_version' => '1.5.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-ORM-conf.php');
return $conf;